title: Antide Duraffour Mathematical Website
author:
  name: Antide Duraffour
  email: antide.duraffour[arobase]univ-grenoble-alpes.fr

description: >
  I am a postdoctoral researcher in Université Grenobles Alpes working in semiclassical analysis and numerical analysis.

theme: minima

plugins:
  - jekyll-feed
  - jekyll-seo-tag

sass:
  quiet_deps: true
  silence_deprecations: [import]

minima:
  skin: classic

  nav_pages:
    - publications.md
    - contact.md
    - cours.md
    - activites.md
    
  show_excerpts: false


